---
title: "simpleRegress"
author: "put your name here"
date: "Fall 2020"
output: html_document
---

```{r setupR, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model


```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
```

## set up python stuff

```{r initial-setup, eval=T, echo=FALSE, include=FALSE}
#install.packages('reticulate')
reticulate::virtualenv_create('testEnv')
reticulate::use_virtualenv('testEnv')
reticulate::virtualenv_install('testEnv', packages = 'numpy')
reticulate::virtualenv_install('testEnv', packages = 'matplotlib')
reticulate::virtualenv_install('testEnv', packages = 'pandas')
reticulate::virtualenv_install('testEnv', packages = 'scipy')

reticulate::virtualenv_install('testEnv', packages = 'plotnine')
reticulate::virtualenv_install('testEnv', packages = 'dpython')
#reticulate::virtualenv_install('testEnv', packages = 'sklearn')
```


## Setup Block
```{r setupP, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
reticulate::use_virtualenv('testEnv')
```

```{python}
import pandas as pd
#from plotnine import * 
import plotnine as p9
#from pandas import *
import pandas as pd
  
# reading dataset
df = pd.read_csv("BEARS.csv")
print(df)
  
p9.ggplot(df) + p9.aes(x="HEADLEN") + p9.geom_histogram()
p9.ggplot(df) + p9.aes(x="HEADLEN", y="LENGTH") + p9.geom_point() + p9.geom_smooth(method = 'lm')

```
